<a href="https://colab.research.google.com/github/aim56009/AI-MA_project/blob/main/Chew.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%matplotlib inline

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import pickle
import torchvision.transforms.functional as TF 

from torch.utils.data import DataLoader
from torch.utils.data.dataset import Dataset
import glob
import os

import random
import click
import sklearn
import sklearn.model_selection
from collections import defaultdict
from sklearn.metrics import accuracy_score
from pathlib import Path
import sys
from torch import optim
from torch.optim import lr_scheduler
from functools import partial
import matplotlib.pyplot as plt

In [3]:
!git clone https://github.com/aim56009/AI-MA_project.git

fatal: destination path 'AI-MA_project' already exists and is not an empty directory.


#Dataloader

In [4]:
batch_size = 1 
PATH_TO_DATA = "AI-MA_project/pianoroll"
workers = 0

In [5]:
class MusicDataset(Dataset):

    def __init__(self, data_dir, transforms=None):
        self.transforms = transforms
        self.data_dir = data_dir

        labels = ["voice_0", "voice_1", "voice_2", "voice_3", "voice_all"]
        self.labels = labels
        self.pr_dict = {}
        len_list = []

        for iLabel in range(len(labels)):
            
            if iLabel == 4:   
                voice_files = []
                file_names = sorted(glob.glob(os.path.join(PATH_TO_DATA, self.labels[iLabel], "*.pkl")))   
                for name in file_names:
                    with open(name ,'rb') as f: 
                        loaded_obj = pickle.load(f)  
                        voice_files.append(loaded_obj) 
                        len_list.append(len(loaded_obj.T))                             
                self.pr_dict[self.labels[iLabel]] = voice_files 
                self.pr_dict["length"] = len_list
            
            else:
                voice_files = []
                file_names = sorted(glob.glob(os.path.join(PATH_TO_DATA, self.labels[iLabel], "*.pkl")))   
                for name in file_names:
                    with open(name ,'rb') as f: 
                        loaded_obj = pickle.load(f)     
                        voice_files.append(loaded_obj)                              
                self.pr_dict[self.labels[iLabel]] = voice_files 
                                        

    def __len__(self):
      
        return len(self.pr_dict[self.labels[0]])

    def __getitem__(self, idx):          

        out_list = []
        for key, value in self.pr_dict.items():
            out_list.append(self.pr_dict[key][idx])                  
        v0 = torch.tensor(out_list[0].T)
        v1 = torch.tensor(out_list[1].T)
        v2 = torch.tensor(out_list[2].T)
        v3 = torch.tensor(out_list[3].T)
        v_all = torch.tensor(out_list[4].T) 
        length = self.pr_dict["length"][idx]

        return (v0, v1, v2, v3, v_all, length)

In [6]:
dataset = MusicDataset(PATH_TO_DATA)
loader = torch.utils.data.DataLoader(dataset,batch_size=batch_size, shuffle=False, num_workers=workers, drop_last=True)

In [7]:
dataset[326][0].shape

torch.Size([576, 128])

In [8]:
"""
0 = next(iter(loader))[0]
v1 = next(iter(loader))[1]
v2 = next(iter(loader))[2]
v3 = next(iter(loader))[3]
v4 = next(iter(loader))[4]
label = next(iter(loader))[5]

voices = next(iter(loader))[0:5]
"""

'\n0 = next(iter(loader))[0]\nv1 = next(iter(loader))[1]\nv2 = next(iter(loader))[2]\nv3 = next(iter(loader))[3]\nv4 = next(iter(loader))[4]\nlabel = next(iter(loader))[5]\n\nvoices = next(iter(loader))[0:5]\n'

# Chew


In [9]:
!pip3 install partitura

In [10]:
import partitura
import numpy as np
import os
import pickle

In [11]:
name = "chor326.xml"
part = partitura.load_musicxml(name)

In [12]:
chew_sep = partitura.musicanalysis.estimate_voices(part, monophonic_voices=True)
#chew_sep_

In [13]:
pos_zero = np.where(chew_sep==1)
pos_one = np.where(chew_sep==2)
pos_two = np.where(chew_sep==3)
pos_three = np.where(chew_sep==4)


pos_zero,pos_one,pos_two,pos_three

((array([  0,   6,  10,  11,  15,  20,  25,  29,  30,  34,  42,  43,  47,
          48,  51,  54,  58,  62,  66,  67,  71,  74,  80,  84,  88,  92,
          96,  97, 102, 106, 107, 112, 118, 122, 126, 130, 131, 135, 139,
         143, 145, 149, 150, 154, 157, 161, 165, 166, 171, 175, 179, 181,
         185, 189, 193, 197]),),
 (array([  1,   4,   7,  12,  16,  19,  21,  26,  31,  35,  38,  39,  44,
          55,  59,  63,  69,  72,  75,  78,  79,  81,  85,  89,  93,  98,
         103, 108, 113, 119, 123, 127, 132, 136, 140, 144, 146, 151, 158,
         162, 167, 170, 172, 176, 182, 186, 190, 194, 198]),),
 (array([  2,   8,  13,  17,  22,  24,  27,  32,  36,  40,  45,  49,  52,
          56,  60,  64,  68,  76,  82,  86,  90,  94,  99, 101, 104, 109,
         111, 114, 116, 117, 120, 124, 128, 133, 137, 141, 147, 152, 155,
         156, 159, 163, 168, 173, 177, 183, 187, 191, 195, 199]),),
 (array([  3,   5,   9,  14,  18,  23,  28,  33,  37,  41,  46,  50,  53,
          57,  61,  65

In [14]:
note_array_zero = partitura.utils.ensure_notearray(part)[pos_zero]
note_array_one = partitura.utils.ensure_notearray(part)[pos_one]
note_array_two = partitura.utils.ensure_notearray(part)[pos_two]
note_array_three = partitura.utils.ensure_notearray(part)[pos_three]

In [38]:
pr_zero = partitura.utils.compute_pianoroll(note_array_zero,time_unit = "beat",time_div = 12)
pr_zero = pr_zero.toarray()

pr_one = partitura.utils.compute_pianoroll(note_array_one,time_unit = "beat",time_div = 12)
pr_one = pr_one.toarray()

pr_two = partitura.utils.compute_pianoroll(note_array_two,time_unit = "beat",time_div = 12)
pr_two = pr_two.toarray()

pr_three = partitura.utils.compute_pianoroll(note_array_three,time_unit = "beat",time_div = 12)
pr_three = pr_three.toarray()


In [39]:
part_zero = part[0]
part_one = part[1]
part_two = part[2]
part_three = part[3]

In [40]:
pr_zero_ori = partitura.utils.compute_pianoroll(part_zero, time_unit = "beat",time_div = 12)
v0 = pr_zero_ori.toarray()

pr_one_ori = partitura.utils.compute_pianoroll(part_one, time_unit = "beat",time_div = 12)
v1 = pr_one_ori.toarray()

pr_two_ori = partitura.utils.compute_pianoroll(part_two, time_unit = "beat",time_div = 12)
v2 = pr_two_ori.toarray()

pr_three_ori = partitura.utils.compute_pianoroll(part_three, time_unit = "beat",time_div = 12)
v3 = pr_three_ori.toarray()

pr_ori = partitura.utils.compute_pianoroll(part, time_unit = "beat",time_div = 12)
v_all = pr_ori.toarray()

In [18]:
#pr_zero_ori.shape, pr_one_ori.shape,pr_two_ori.shape, pr_three_ori.shape, pr_ori.shape
#pr_zero.shape, pr_one.shape,pr_two.shape, pr_three.shape

In [20]:
#np.sum(pr_zero_ == pr_zero) - 61440, np.sum(pr_one == pr_one_) - 61440 ,np.sum(pr_two == pr_two_) - 61440,np.sum(pr_three_ == pr_three) - 61440

In [ ]:
loss = nn.CrossEntropyLoss(reduction="mean")
"""
pr_zero = torch.tensor(pr_zero).type(torch.FloatTensor)
v0 = torch.tensor(v0).type(torch.FloatTensor)

pr_one = torch.tensor(pr_one).type(torch.FloatTensor)
v1 = torch.tensor(v1).type(torch.FloatTensor)

pr_two = torch.tensor(pr_two).type(torch.FloatTensor)
v2 = torch.tensor(v2).type(torch.FloatTensor)

pr_three = torch.tensor(pr_three).type(torch.FloatTensor)
v3 = torch.tensor(v3).type(torch.FloatTensor)

v0 = v0.squeeze()
v1 = v1.squeeze()
v2 = v2.squeeze()
v3 = v3.squeeze()
        
losses = loss(pr_zero, v0) + loss(pr_one, v1) + loss(pr_two, v2) + loss(pr_three, v3)
losses
"""

In [49]:
from sklearn.metrics import accuracy_score

acc_v0 = accuracy_score(torch.tensor(pr_zero), v0)
acc_v1 = accuracy_score(torch.tensor(pr_one), v1)
acc_v2 = accuracy_score(torch.tensor(pr_two),v2)
acc_v3 = accuracy_score(torch.tensor(pr_three), v3)

In [51]:
acc_v0,acc_v1,acc_v2,acc_v3

(0.96875, 0.9765625, 0.9921875, 1.0)